language: haxe

haxe:
  - 3.4.7
  - development

sudo: false

dist: trusty

addons:
  apt:
    packages:
      - mono-devel

install:
  - haxelib git hxparse https://github.com/Simn/hxparse --never
  - haxelib install hx3compat

hxml:
  - build.hxml

matrix:
  allow_failures:
    - haxe: 3.4.7